### ISSUE TITLE
User id is not sent correctly

### ISSUE THREAD

**Issue by sunildhiman90** [getsentry/sentry-kotlin-multiplatform#470]
### Platform

Apple

### Installed

Swift Package Manager

### Version

0.19.0

### Steps to Reproduce

I am setting user via setupUser on app startup in compose multiplatform app, but while testing some crash on som other screen,  then its sending some other id may be device id guess.
In dashboard its showing that id, but not the logged in user id im setting on app startup.

### Expected Result

It should use the user id setup via setupUser

### Actual Result

Its using different id automatically, i guess device id.

**Comment by buenaflor** [comment]
I just used the following code which works for me on iOS:

```Kotlin
Sentry.configureScope {
    it.user = User().apply {
        username = "John Doe"
        email = "john@doe.com"
        id = "random-id"
    }
}
```

<img width="969" height="186" alt="Image" src="https://github.com/user-attachments/assets/d679813b-8166-425a-9520-80739028fa53" />

Could you show an example code of how you use it?

**Comment by sunildhiman90** [comment]
I tried adding username as well, but still not working. 
I tried using configureScope as well, but still its showing device id in place of user is in context.

**Comment by buenaflor** [comment]
if I understand correclty you're testing it with crashes. afaict this issue is related to #477 

so once we ship this feature this should be fixed

**Comment by sunildhiman90** [comment]
Hi, this is still not working for me as expected in `0.24.0` version in ios.
This is my init setup:

```
Sentry.init { options ->
        options.dsn = BuildKonfig.SENTRY_URL
        // Adds request headers and IP for users, for more info visit:
        // https://docs.sentry.io/platforms/kotlin/guides/kotlin-multiplatform/data-management/data-collected/
        options.sendDefaultPii = true

        // Just for testing, in production set it to false
        options.debug = true

        // TODO, need to set build number here
        options.release = "1"
    }
}
```

Stil sending device id in place of user id in unhandled test crash, But works fine using `captureException`
